services:
  bot:
    container_name: crypto-trading-bot
    image: node:20-alpine
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    ports:
        - "8080:8080"
    command: npm start
